name: codepan
description: General purpose library for dart.
version: 2.0.0
author: Jeffrey Concha
homepage: https://github.com/jeffreyconcha/codepan.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_settings: ^4.1.0
  audioplayers: ^0.18.3
  cached_network_image: ^3.0.0
  connectivity: ^3.0.3
  equatable: ^2.0.0
  exif: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_native_image: ^0.0.6
  flutter_svg: ^0.21.0+1
  html_unescape: ^2.0.0
  image: ^3.0.2
  inflection3: ^0.5.3+2
  intl: ^0.17.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.3
  pull_to_refresh: ^1.6.5
  sqflite_sqlcipher: ^2.0.0
  time_ago_provider: ^4.0.0
  video_player: ^2.1.1
  visibility_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


